### ISSUE TITLE
Invert legend

### ISSUE THREAD

**Issue by Stophface** [timwis/leaflet-choropleth#14]
Is there a way to invert the legend?

**Comment by Stophface** [comment]
[...]

```
// Add min & max
div.innerHTML = '<div class="labels"><div class="min">' + limits[0] + '</div> \
        <div class="max">' + limits[limits.length - 1] + '</div></div>'

limits.forEach(function (limit, index) {
  labels.push('<li style="background-color: ' + colors[3 - index] + '"></li>')
})
```

[...]

**Comment by timwis** [comment]
@Stophface you can also use javascript's [`Array.prototype.reverse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse) function. For example, you could just add `labels.reverse()` on [this line](https://github.com/timwis/leaflet-choropleth/blob/gh-pages/examples/legend/demo.js#L41) to reverse the array before they're put into the `<ul>`. Another alternative would be to use `.unshift` instead of `.push` to prepend the `<li>`s instead of appending them.
